"""Tests for envpack.restore module."""

import json
import os
import tempfile
from pathlib import Path

import pytest

from envpack.restore import (
    apply_to_current_process,
    generate_export_script,
    write_restore_script,
)


@pytest.fixture
def snapshot_file(tmp_path):
    data = {"APP_ENV": "production", "DB_HOST": "localhost", "SECRET": "s3cr3t"}
    p = tmp_path / "snap.json"
    p.write_text(json.dumps(data))
    return str(p)


def test_generate_export_script_bash(snapshot_file):
    script = generate_export_script(snapshot_file, shell="bash")
    assert "export APP_ENV='production'" in script
    assert "export DB_HOST='localhost'" in script
    assert script.startswith("# Generated by envpack")


def test_generate_export_script_fish(snapshot_file):
    script = generate_export_script(snapshot_file, shell="fish")
    assert "set -x APP_ENV 'production'" in script


def test_generate_export_script_unsupported_shell(snapshot_file):
    with pytest.raises(ValueError, match="Unsupported shell"):
        generate_export_script(snapshot_file, shell="powershell")


def test_generate_export_script_quotes_special_chars(tmp_path):
    data = {"MSG": "it's alive"}
    p = tmp_path / "snap.json"
    p.write_text(json.dumps(data))
    script = generate_export_script(str(p), shell="bash")
    assert "MSG" in script
    assert "alive" in script


def test_write_restore_script_creates_file(snapshot_file, tmp_path):
    out = str(tmp_path / "restore.sh")
    write_restore_script(snapshot_file, out)
    assert Path(out).exists()
    content = Path(out).read_text()
    assert "export" in content


def test_apply_to_current_process(snapshot_file):
    applied = apply_to_current_process(snapshot_file)
    assert os.environ.get("APP_ENV") == "production"
    assert os.environ.get("DB_HOST") == "localhost"
    assert "APP_ENV" in applied


def test_apply_to_current_process_filtered_keys(snapshot_file):
    applied = apply_to_current_process(snapshot_file, keys=["APP_ENV"])
    assert "APP_ENV" in applied
    assert "DB_HOST" not in applied
