"""Restore environment variable snapshots to shell export scripts."""

import os
from pathlib import Path
from typing import Optional

from envpack.snapshot import load


def generate_export_script(snapshot_path: str, shell: str = "bash") -> str:
    """Generate a shell export script from a snapshot file."""
    snapshot = load(snapshot_path)

    if shell == "fish":
        lines = [f"set -x {key} {_quote_value(value, shell)}" for key, value in snapshot.items()]
    elif shell in ("bash", "zsh", "sh"):
        lines = [f"export {key}={_quote_value(value, shell)}" for key, value in snapshot.items()]
    else:
        raise ValueError(f"Unsupported shell: {shell}")

    header = f"# Generated by envpack — restore from {snapshot_path}\n"
    return header + "\n".join(lines) + "\n"


def _quote_value(value: str, shell: str) -> str:
    """Quote a value for safe shell usage."""
    escaped = value.replace("'", "'\\''")
    return f"'{escaped}'"


def write_restore_script(snapshot_path: str, output_path: str, shell: str = "bash") -> None:
    """Write a restore script to a file."""
    script = generate_export_script(snapshot_path, shell)
    Path(output_path).write_text(script)


def apply_to_current_process(snapshot_path: str, keys: Optional[list] = None) -> dict:
    """Apply snapshot variables to the current process environment.

    Returns a dict of the variables that were applied.
    """
    snapshot = load(snapshot_path)

    if keys is not None:
        snapshot = {k: v for k, v in snapshot.items() if k in keys}

    for key, value in snapshot.items():
        os.environ[key] = value

    return snapshot
